image: registry.gitlab.com/lepovirta/dis/lepo-build:latest

stages:
- build
- pages

workflow:
  rules:
    - if: $CI_MERGE_REQUEST_ID
    - if: $CI_COMMIT_BRANCH == "master"

build:
  stage: build
  script:
  - ./build_blocklist.sh
  artifacts:
    paths:
    - blocklist.txt
    expire_in: 1 days

pages:
  stage: pages
  script:
  - mkdir -p public
  - cp index.html public/
  - mv blocklist.txt public/
  dependencies:
  - build
  artifacts:
    paths:
    - public
    expire_in: 10 days
  rules:
  - if: $CI_COMMIT_BRANCH == "master"

